# Generated by Django 3.0.8 on 2022-07-01 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='grouppurchase',
            table='group_purchase',
        ),
    ]
