# Generated by Django 3.0.8 on 2022-07-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220702_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='duration',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='grouppurchase',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
