# Generated by Django 3.0.8 on 2022-07-02 00:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220702_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vegan',
            name='level',
            field=models.CharField(choices=[('Vegan', 'Vegan'), ('Lacto', 'Lacto'), ('Ovo', 'Ovo'), ('Lacto Ovo', 'Lacto Ovo'), ('Pesco', 'Pesco'), ('Pollo', 'Pollo'), ('Flexitarian', 'Flexitarian'), ('NonVegan', 'NonVegan')], max_length=11),
        ),
    ]
