# Generated by Django 3.0.8 on 2022-07-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220702_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='co2cal',
            name='level',
            field=models.IntegerField(),
        ),
    ]
